USE [master]
GO

/****** Object:  Database [FPL_DAOTAO]    Script Date: 8/10/2022 3:25:10 AM ******/
CREATE DATABASE [FPL_DAOTAO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FPL_DAOTAO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\FPL_DAOTAO.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FPL_DAOTAO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\FPL_DAOTAO_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FPL_DAOTAO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FPL_DAOTAO] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FPL_DAOTAO] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FPL_DAOTAO] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FPL_DAOTAO] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FPL_DAOTAO] SET ARITHABORT OFF 
GO

ALTER DATABASE [FPL_DAOTAO] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FPL_DAOTAO] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FPL_DAOTAO] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FPL_DAOTAO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FPL_DAOTAO] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FPL_DAOTAO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FPL_DAOTAO] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FPL_DAOTAO] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FPL_DAOTAO] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FPL_DAOTAO] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FPL_DAOTAO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FPL_DAOTAO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FPL_DAOTAO] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FPL_DAOTAO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FPL_DAOTAO] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FPL_DAOTAO] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FPL_DAOTAO] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FPL_DAOTAO] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FPL_DAOTAO] SET  MULTI_USER 
GO

ALTER DATABASE [FPL_DAOTAO] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FPL_DAOTAO] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FPL_DAOTAO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FPL_DAOTAO] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FPL_DAOTAO] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FPL_DAOTAO] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [FPL_DAOTAO] SET QUERY_STORE = OFF
GO

ALTER DATABASE [FPL_DAOTAO] SET  READ_WRITE 
GO


